import beef1 from "../assets/products/beef1.png";
import beef2 from "../assets/products/beef2.jpg";
import cleaning1 from "../assets/products/cleaning1.png";
import cleaning2 from "../assets/products/cleaning2.png";
import juice1 from "../assets/products/juice1.png";
import juice2 from "../assets/products/juice2.png";
import plate from "../assets/products/plates.png";
import milk from "../assets/products/milk.jpg";
import paneer from "../assets/products/paneer.jpg";
import fish from "../assets/products/fish.png";
import crab from "../assets/products/crab.png";

export const productData = [
  {
    id: 1,
    name: "Fresh Milk",
    category: "Dairy",
    price: 3.99,
    image: milk,
    onSale: true,
    saleBadge: "On Sale",
  },
  {
    id: 2,
    name: "Organic Paneer",
    category: "Dairy",
    price: 5.49,
    image: paneer,
    onSale: false,
  },
  {
    id: 3,
    name: "Prime Beef Steak",
    category: "Meat",
    price: 15.99,
    image: beef1,
    onSale: true,
    saleBadge: "On Sale",
  },
  {
    id: 4,
    name: "Beef Ribs",
    category: "Meat",
    price: 18.49,
    image: beef2,
    onSale: false,
  },
  {
    id: 5,
    name: "Fresh Orange Juice",
    category: "Beverages",
    price: 4.99,
    image: juice1,
    onSale: true,
    saleBadge: "20% Off",
  },
  {
    id: 6,
    name: "Lemon Juice",
    category: "Beverages",
    price: 3.29,
    image: juice2,
    onSale: false,
  },
  {
    id: 7,
    name: "Bottled Water",
    category: "Beverages",
    price: 1.29,
    image: juice2,
    onSale: false,
  },
  {
    id: 8,
    name: "Cleaning Spray",
    category: "Cleaning",
    price: 6.99,
    image: cleaning1,
    onSale: true,
    saleBadge: "10% Off",
  },
  {
    id: 9,
    name: "Cleaning Wipes",
    category: "Cleaning",
    price: 4.99,
    image: cleaning2,
    onSale: false,
  },
  {
    id: 10,
    name: "Premium Fish",
    category: "Seafood",
    price: 13.49,
    image: fish,
    onSale: true,
    saleBadge: "On Sale",
  },
  {
    id: 11,
    name: "Crab Legs",
    category: "Seafood",
    price: 19.99,
    image: crab,
    onSale: false,
  },
  {
    id: 12,
    name: "BBQ Chicken Wings",
    category: "Meat",
    price: 9.99,
    image: beef1,
    onSale: true,
    saleBadge: "15% Off",
  },
  {
    id: 13,
    name: "Vegetable Plate",
    category: "Produce",
    price: 6.99,
    image: plate,
    onSale: true,
    saleBadge: "10% Off",
  },
  {
    id: 14,
    name: "Grilled Beef Burger",
    category: "Meat",
    price: 8.49,
    image: beef2,
    onSale: false,
  },
  {
    id: 15,
    name: "Farm Fresh Crab",
    category: "Seafood",
    price: 14.99,
    image: crab,
    onSale: true,
    saleBadge: "20% Off",
  },
  {
    id: 16,
    name: "Whole Chicken",
    category: "Meat",
    price: 10.99,
    image: beef1,
    onSale: true,
    saleBadge: "On Sale",
  },
  {
    id: 17,
    name: "Beef Tacos",
    category: "Meat",
    price: 7.99,
    image: beef2,
    onSale: false,
  },
  {
    id: 18,
    name: "Fresh Salmon",
    category: "Seafood",
    price: 16.99,
    image: fish,
    onSale: true,
    saleBadge: "On Sale",
  },
  {
    id: 19,
    name: "Natural Cleaner",
    category: "Cleaning",
    price: 5.99,
    image: cleaning1,
    onSale: false,
  },
  {
    id: 20,
    name: "Dishwashing Liquid",
    category: "Cleaning",
    price: 2.99,
    image: cleaning2,
    onSale: true,
    saleBadge: "5% Off",
  },
];
